import type {Metadata} from "next";
import {Wix_Madefor_Display} from "next/font/google";
import "./globals.css";
import React from "react";
import Header from "@/app/components/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const gabriela = Wix_Madefor_Display({
    weight: ['400'],
    style: ['normal'],
    subsets: ['cyrillic'],
});

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body className={gabriela.className}>
                <Header/>
                {children}
            </body>
        </html>
    );
}
